### ISSUE TITLE
test/unicode.h licensed under GPL-2.0

### ISSUE THREAD

**Issue by scarabeusiv** [myint/cppclean#143]
We are trying to ship cppclean in openSUSE and we noticed tiny issue with licensing:

https://github.com/myint/cppclean/blob/master/test/unicode.h Is taken from https://zeroc.com/downloads/ice that is licensed under GPL-2.0 while this package is licensed under Apache-2.0.

This is unfortunately not compatible as per https://www.apache.org/licenses/GPL-compatibility.html

Could you please check and tweak it accordingly?

**Comment by myint** [comment]
I'm fine with removing it.

**Comment by myint** [comment]
https://github.com/myint/cppclean/commit/998e80d02eb27fa7a59ac23db41ae3854f3c2d19
