### ISSUE TITLE
Python errors while using cppclean

### ISSUE THREAD

**Issue by srpgilles** [myint/cppclean#59]
Hi,

I've tried today to run Cppclean on my code base, mostly for the header related feature. It didn't work well though; I had to modify slightly the Python sources so that it can go until the end. 

These modifications are far from being clean (I'm far to be a Python expert!) but should point out some cases that might fail while using your software; the point where they fail in my code were clean (it might be due to new C++11 feature, such as alias with using or '= default' for class special members).

Best regards,

Sébastien

**Comment by srpgilles** [comment]
I don't know how to attach files; so I've copied the git diff output below:

diff --git a/cpp/ast.py b/cpp/ast.py
index 688aa49..a28496d 100644
--- a/cpp/ast.py
+++ b/cpp/ast.py
@@ -1002,7 +1002,7 @@ class ASTBuilder(object):
         # Handle templatized ctors.
         elif name.name == '>':
             index = 1
-            while return_type_and_name[index].name != '<':
+            while index < len(return_type_and_name) and return_type_and_name[index].name != '<':
                 index += 1
             template_portion = return_type_and_name[index:] + [name]
             del return_type_and_name[index:]
@@ -1696,7 +1696,7 @@ class ASTBuilder(object):
     def handle_default(self):
         token = self._get_next_token()
         assert token.token_type == tokenize.SYNTAX
-        assert token.name == ':'
+        #assert token.name == ':'
 
     def handle_if(self):
         pass
@@ -1756,5 +1756,5 @@ def builder_from_source(source, filename, quiet=False):
 
 def assert_parse(value, message):
     """Raise ParseError on token if value is False."""
-    if not value:
+    if False and not value:
         raise ParseError(message)
diff --git a/cpp/find_warnings.py b/cpp/find_warnings.py
index ec5e1e5..d62b05a 100644
--- a/cpp/find_warnings.py
+++ b/cpp/find_warnings.py
@@ -294,9 +294,12 @@ class WarningHunter(object):
                 return
 
             # TODO(nnorwitz): do proper check for ref/pointer/symbol.
-            name = file_use_node[1].normalized_filename
-            if name in file_uses:
-                file_uses[name] |= USES_DECLARATION
+            try:
+                name = file_use_node[1].normalized_filename
+                if name in file_uses:
+                    file_uses[name] |= USES_DECLARATION
+            except:
+                return
 
         def _add_variable(node, namespace):
             if node.reference or node.pointer:

**Comment by myint** [comment]
If you put the diff inside [triple-backtick blocks](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) labeled `diff`, GitHub will display it better.

**Comment by srpgilles** [comment]
Thanks, I've just done it.

**Comment by r-e-d** [comment]
If you can extract some minimal code sample from your code base, it will be easier for us to fix specific issues.

**Comment by r-e-d** [comment]
Hi,

cppclean has now a better support for C++11 features. I think the proposed changes are no longer relevant. So I close this issue.

Feel free to open new issues if you find new bugs.
