### ISSUE TITLE
Nested templates yield token exception

### ISSUE THREAD

**Issue by chrizke** [myint/cppclean#72]
From C++11 on, nested templates do not require a whitespace between closing '>' anymore.

Before C++11:
```C++
std::vector<std::vector<double> >
```
C++11:
```C++
std::vector<std::vector<double>>
```
The second version yields a token exception.

**Comment by myint** [comment]
Can you provide the error message? Also, what version of cppclean are you using?

Thanks

**Comment by chrizke** [comment]
I'm using 0.2.6.

The error message is

>Got exception in D:\cppclean\MyClass.h @ Token('std', 164, 167) []
>Got exception in D:\cppclean\MyClass.h @ Token('class', 77, 82) []
>D:\cppclean\MyClass.h: parsing error [Token('std', 164, 167), Token('::', 167, 169), Token('vector', 169, 175), Token('<', 175, 176), Token('std', 176, 179), Token('::', 179, 181), Token('pair', 181, 185), Token('<', 185, 186), Token('double', 186, 192), Token(',', 192, 193), Token('OtherClass', 194, 204), Token('>>', 204, 206)]

and MyClass.h is

```C++
#pragma once

#include "OtherClass.h"

#include <vector>
#include <utility>

class CMyClass
{
public:
  CMyClass();
    
 private:
   COtherClass & mOtherClass;
   std::vector<std::pair<double, OtherClass>> myVec;
};

```

**Comment by r-e-d** [comment]
This is fixed by my latest commit.

Thanks for the report.
