### ISSUE TITLE
std::function yields token exception

### ISSUE THREAD

**Issue by chrizke** [myint/cppclean#73]
Similar to https://github.com/myint/cppclean/issues/72 a token exception is raised when parsing a C++11 std::function. See below for error message and code example. Version is 02db685a29e4352b53b5f278414c481f2a8b4f3c.

#### Error message
>Got exception in MyClass.h @ Token('std', 92, 95) []
>Got exception in MyClass.h @ Token('class', 37, 42) []
>MyClass.h: parsing error (Token('>', 126, 127), [Token('std', 92, 95), Token('::', 95, 97), Token('function', 97, 105), Token('<', 105, 106)], [Token('double', 111, 117), Token(',', 117, 118), Token('double', 119, 125)])

#### Code example
````cpp
#pragma once

#include <functional>

class CMyClass
{
public:
  CMyClass();
    
private:
  std::function<void(double, double)> mFunctor;
};
````

**Comment by r-e-d** [comment]
Fixed by this commit.

Thanks for the bug report.
