### ISSUE TITLE
Unexpected token parsing errors for C++11 code

### ISSUE THREAD

**Issue by rakhimov** [myint/cppclean#75]
Cppclean used to work before transitioning to C++11.
Running on valid C++11 code causes parsing errors of the form:
Token(u'return', 3189, 3195)

There are no line numbers in error messages to see what is wrong.
Header code in https://github.com/rakhimov/scram can be used to get the errors.

**Comment by rakhimov** [comment]
Commit 4da34399552c1e97747f906f2423634ce4ca2eac solved the main problem.
Another issue seems to be with empty initializer lists within constructors:
```cpp
A::A() : B::B({}), member(value) {}
```
The real example is in `expression.cc` file.

**Comment by rakhimov** [comment]
C++11 using declaration/alias seems not be supported.

```cpp
using alias = A<B>;
```

**Comment by samoatesgames** [comment]
Struct initializers in-general seem to cause issues.
The following fails for example:

`User() : m_id{}, m_serviceID(USER_ID_INVALID) {}`

**Comment by r-e-d** [comment]
Closing this issue as this seems to work now.

**Comment by waldyrious** [comment]
In case this is useful to others, this issue still occurs for functions written in old-style (pre-ISO) C with a declaration section *before* the function's opening bracket, like in this example [from Wikipedia](https://en.wikipedia.org/wiki/Indent_style#K.26R_style):

```c
/* Original pre-ISO C style without function prototypes */
int main(argc, argv)
    int   argc;
    char  *argv[];
{
    ...
}
```

**Comment by lucapalano** [comment]
cppclean v0.13

In my case, this occurs with C++ braced Initialization . Here is an example:
```
#ifndef _TEST_HPP_

#define _TEST_HPP_

class test {

private:
    bool check{true};

};

#endif
```
causes:
`test.hpp: parsing error: unexpected token: Token(u'true', 78, 82)`

Removing the braced Initialization fixed the issue, as follow:
```
#ifndef _TEST_HPP_

#define _TEST_HPP_

class test {

private:
    bool check = true;

};

#endif
```
