### ISSUE TITLE
cppclean thinks a forward declaration is not used

### ISSUE THREAD

**Issue by jwpeterson** [myint/cppclean#77]
cppclean prints the following warning:
```
cppclean_test.h:7: 'A' not used
```

for the sample cppclean_test.h below:
```
// A function template
template<class T> void foo();

// This forward declaration really is used in the full specialization
// below, but cppclean thinks it is not.  The code will not compile
// without it.
class A;

// A full specialization of foo declared before A.
template<>
void foo<A>();

// Actual class definition.
class A {};
```

It's not a crash so I don't think it counts as a bug, just a warning that I have to ignore a lot, as I use a framework that makes extensive use of this pattern.

**Comment by myint** [comment]
Should the title refer to "forward declaration" rather than "typedef"?

**Comment by jwpeterson** [comment]
Yes, you're right of course!

**Comment by r-e-d** [comment]
Thanks for the bug report. This should be fixed by my last commit.
