### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

### ISSUE THREAD

**Issue by amai2012** [myint/cppclean#79]
cppclean 0.6 tells me
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)`

How can I find out the problem - e.g. which file is triggering the message?

**Comment by myint** [comment]
Try `--verbose`.

**Comment by amai2012** [comment]
That's already specified.

**Comment by myint** [comment]
Please provide the full command line input and full output.

Thanks

**Comment by amai2012** [comment]
Commandline is like 
```
cppclean --include-path=project1 --include-path= project2/include  --verbose .
```
where actually the list of includes is a bit longer than posted.
The output is:
```
Traceback (most recent call last):
  File "/usr/bin/cppclean", line 140, in <module>
    sys.exit(main())
  File "/usr/bin/cppclean", line 102, in main
    exclude_patterns=args.exclude_patterns))
  File "/usr/bin/cppclean", line 69, in find_files
    exclude_patterns)]
  File "/usr/bin/cppclean", line 42, in match_file
    if base_name.startswith('.'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
```
Actually I am using an up-to-date cygwin 64bit and
```
$ cppclean --version
cppclean 0.6
```

**Comment by myint** [comment]
This looks like a Python 2 problem. Let me know if 793bd44 fixes it.

**Comment by amai2012** [comment]
That issue got solved. Thanks for the quick fix!
 I have another issue which I will report in a new report!
