### ISSUE TITLE
Crash in  _get_method on invalid/incomplete code

### ISSUE THREAD

**Issue by amai2012** [myint/cppclean#82]
Running cppclean on this invalid/incomplete code
~~~c++
#define FOO

extern void foo(
~~~
triggers a crash:
~~~
Traceback (most recent call last):
  File "/usr/bin/cppclean", line 145, in <module>
    sys.exit(main())
  File "/usr/bin/cppclean", line 120, in main
    entire_ast = list([_f for _f in builder.generate() if _f])
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 668, in generate
    result = self._generate_one(token)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 757, in _generate_one
    return self._get_method(temp_tokens, 0, None, False)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 989, in _get_method
    last_token = parameters.pop()    # Remove trailing ')'.
IndexError: pop from empty list
~~~

**Comment by r-e-d** [comment]
I'm not sure that we want to handle incomplete code.

**Comment by myint** [comment]
I agree with @r-e-d. One of the documented ["non-goals"](https://github.com/myint/cppclean#non-goals) in the readme is "Handling invalid C++ source gracefully".

**Comment by amai2012** [comment]
Since cppclean seems to stop processing when running across such a problem usability is suffering. Due to incomplete include search PATHs, shortcoming during preprocessing(?) code may look incomplete - while it is not in the real world use-case.

**Comment by r-e-d** [comment]
cppclean does not do preprocessing so yes we need to handle some 'invalid' code. But in this case, I don't see how we can hit this crash with a valid input. Do you have a sample where we hit this case with a valid source ?

Also I think cppclean only stops parsing the current file when crashing, it should continue to analyse the other files. But maybe I'm wrong about that and in that case we should see if we can fix it.

**Comment by myint** [comment]
@amai2012, that is a good point. I'll take a look.
