### ISSUE TITLE
KeyError raised

### ISSUE THREAD

**Issue by gluttony38** [myint/cppclean#84]
Hi,

I have a python KeyError raised when running cppclean, it is in a big project then I'm not sure when exactly it happens.
End of traceback is:
  File "/usr/local/lib/python2.7/site-packages/cpp/find_warnings.py", line 260, in _add_reference
    name = file_use_node[1].filename
KeyError: 1

Note that, I had first installed cppclean through "pip install --upgrade cppclean", and had the same issue in "add_use(name, namespace)" that is, now that I installed from cppclean-master, fixed with (lines with + are lines that fixed the problem):

```python
        def _add_use(name, namespace):
            [...]
            + if isinstance(file_use_node, dict):
            +    return
            # TODO(nnorwitz): do proper check for ref/pointer/symbol.
            name = file_use_node[1].filename
            if name in file_uses:
                file_uses[name] |= USES_DECLARATION
            [...]
```

I then added the same "if isinstance return" in _add_reference(name, namespace) before calling "name = file_use_node[1].filename" an it seems to do the job, but since I'm not sure if this is the right thing to do I prefer filing a new issue, anyway, if you need more information to track this issue do not hesitate to ask.

Thanks and best regards.

**Comment by myint** [comment]
Could you format your code in triple backticks (as per [Markdown](https://guides.github.com/features/mastering-markdown/))? The above currently seems a bit scrambled.

Thanks

**Comment by gluttony38** [comment]
Hi,
Sorry, I haven't seen my "+" have been turned in bullets and code was totally unreadable, I edited my post, please tell me if it's enough.
Thanks.

**Comment by r-e-d** [comment]
Can you post the project producing this error or is it private ? Can you try to find a smaller test case ?

Looking at the code, I don't see how we can end up in this case.I'd like to be able to debug this crash to see if your suggestion is enough or if we need a more complex fix.

**Comment by gluttony38** [comment]
Hi,
I managed to reproduce a small test case, and, after several tests to be able to reproduce it with a smallest possible file, it seems that what is leading to this issue is: we have a function under two namespaces (NS1::**NS2**), defined in an interface and implemented in another class and taking a **const reference** to an object named as **second namespace (NS2)**.
Couldn't attach zip file then just put those two code in files named as specified in a same folder and run cppclean on it:
+ If.h
```C++
#ifndef IF_H_
#define IF_H_

namespace NS1
{
namespace NS2
{
    virtual void func(const NS2& p_ns2) = 0;
}
}

#endif

```
+ Impl.h

```C++
#ifndef IMPL_H_
#define IMPL_H_

#include "If.h"

namespace NS1
{
namespace NS2
{
	virtual void func(const NS2& p_ns2);
}
}

#endif

```

**Comment by r-e-d** [comment]
Thanks for the testcase. I didn't knew you can use the same name for a class and a namespace !

**Comment by gluttony38** [comment]
I didn't knew too, but afterwards I thought, we can name either namespace or class pretty much as we want (in any case with same rules), and bigger the project is more are the odds to come across with both with same name.

**Comment by r-e-d** [comment]
This should be fixed.
