### ISSUE TITLE
--include-path isn't recursive

### ISSUE THREAD

**Issue by JesseJ** [myint/cppclean#85]
Maybe this was done by design, but --include-path isn't recursive. This means instead of doing

--include-path ../src/

I have to do

--include-path ../src/A --include-path ../src/B --include-path ../src/C --include-path ../src/D

This ends up in a rather large command line. Would be nice if I didn't have to.

**Comment by myint** [comment]
This is intended. It is meant to be like `-I` in `gcc`.
