### ISSUE TITLE
cppclean suggests forward declaring something which is an enum

### ISSUE THREAD

**Issue by jwpeterson** [myint/cppclean#86]
But this isn't allowed by the [C++03 standard](http://stackoverflow.com/questions/71416/forward-declaring-an-enum-in-c).  The following simple test code (two files) demonstrates the issue:

myenum.h:
```
enum MyEnum {FOO, BAR, BAZ};
```

cppclean_test4.h:
```
// Header file where enum MyEnum is defined.
#include "myenum.h"

class A
{
  // f takes a reference to MyEnum, but as an enum it can't be forward declared.
  void f(MyEnum & bar);
};
```

cppclean prints:
```
cppclean_test4.h:2: 'myenum.h' does not need to be #included; use a forward declaration instead
```

**Comment by r-e-d** [comment]
Thanks for the report. This is fixed now :)
