### ISSUE TITLE
'using namespace' in header file not taken into account

### ISSUE THREAD

**Issue by WimLeflere** [myint/cppclean#89]
With the following code, I get the message `'namespace_parent.h' does not need to be #included`, which is incorrect.

parent.h
```cpp
namespace parent
{
   class Parent {};
}
```
child.h
```cpp
#include "namespace_parent.h"

using namespace parent;

namespace child
{
   class Child : Parent {};
}
```
The code compiles correctly but 'using namespace' in a header file is bad practice, so it might be better to give a warning that it is better to use full namespaces.

**Comment by WimLeflere** [comment]
Proposal in pull request: #90

**Comment by r-e-d** [comment]
Commit  785f14a should fix the incorrect warning.
