### ISSUE TITLE
coala

### ISSUE THREAD

**Issue by sils1297** [myint/cppclean#93]
Hey, you know us already IIRC, just wanted to let you know that we added CPPClean support in coala (coala-analyzer.org). Usual things apply, this opens it up for several editor plugins, our automatic GitHub pull request review thingy, various analysis data dumps and so on. As always we're open for collaboration but I think we had this discussion so feel free to close this bug when read. :)

Have a nice day!

**Comment by myint** [comment]
Great!

https://github.com/coala-analyzer/coala-bears/commit/812c9750d8212c31e52df541daccfa8cb670d754
